services:
  transmission:
    image: jolcsak/transmission-next:amd64
    platform: linux/amd64
    restart: unless-stopped
    stop_grace_period: 120s
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    tmpfs:
      - /run:rw,nosuid,nodev,size=32m,mode=755
      - /tmp:rw,nosuid,nodev,size=32m,mode=1777
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
